### ISSUE TITLE
Deployment on Vercel,, Render, or Replit

### ISSUE THREAD

**Issue by bestfriendai** [desprit/tg-ai-connector#12]
Can you add instructions to deploy this on a live server?

**Comment by desprit** [comment]
@bestfriendai 

It's already in readme:
https://github.com/desprit/tg-ai-connector#running-in-development

**Comment by bestfriendai** [comment]
I must not be that smart. I tried on all 3 and I couldnt get it to work. Could you send screenshots and step by step process on replit or any other host?

**Comment by desprit** [comment]
The instructions are very straightforward, you install python version 3.10, install dependencies listed in requirements.txt, you create a config file and start python process. If some of these steps don't work, please send me a traceback.

**Comment by bestfriendai** [comment]
I hate to be a bother but I cannot get it to work on heroku, vercel, or replit.

What host do you have it serving on? And do you have a skype/telegram?

**Comment by desprit** [comment]
@bestfriendai 

I'm using a standard ubuntu VPS. 
Please ask your questions here so it can be seen by other people.

**Comment by bestfriendai** [comment]
If you could try to deploy on Repliit or Vercel or Heroku or Render and show the step by step on there that would be great.

**Comment by desprit** [comment]
@bestfriendai 

I won't deploy it anywhere, sorry. Please provide error tracebacks or something I can use to help you otherwise I'm closing it.
