### ISSUE TITLE
Video models from replicate

### ISSUE THREAD

**Issue by bestfriendai** [desprit/tg-ai-connector#13]
Hey, if I were to add a text to video model like https://replicate.com/deforum/deforum_stable_diffusion would would I need to change in the code?

**Comment by desprit** [comment]
You would need to add a corresponding section in this handler:
https://github.com/desprit/tg-ai-connector/blob/master/src/bot.py#L94

And then you would also add a handler for "video" requests to this module:
https://github.com/desprit/tg-ai-connector/blob/master/src/integrations/replicate.py

**Comment by bestfriendai** [comment]
Ok I added the function to the bot and used this code for the video requests

def get_replicate_video_response(prompts: str,
                                 cfg: model.ReplicateNetwork,
                                 max_frames: int = 100,
                                 fps: int = 15) -> Tuple[bytes, Optional[str]]:
  try:
    model = replicate.models.get(cfg.name)
    version, _ = model.versions.get(
      cfg.version)  # explicitly unpack into two variables
  except Exception as e:
    return b"", f"Error while initializing Replicate model: {e}"
  inputs = {
    "max_frames": max_frames,
    "animation_prompts": prompts,
    "angle": "0:(0)",
    "zoom": "0:(1.04)",
    "translation_x": "0:(0)",
    "translation_y": "0:(0)",
    "color_coherence": "Match Frame 0 LAB",
    "sampler": "plms",
    "fps": fps,
  }
  output = None
  for _ in range(2):
    try:
      if settings.debug:
        logger.debug(f">>> Replicate video request for: {prompts}")
      output = version.predict(**inputs)
      logger.debug(f">>> Replicate video response: {output}")
    except replicate.exceptions.ReplicateError as e:
      time.sleep(1)
    except Exception as e:
      return b"", f"Error while getting video: {e}"
    break
  if not output:
    return b"", "Error while getting video response"
  return output, None


but im still getting this error when using the prompt in telegram 

Error while initializing Replicate model: too many values to unpack (expected 2)

**Comment by desprit** [comment]
Because you are unpacking into two variables here:
```
version, _ = model.versions.get(cfg.version)  # explicitly unpack into two variables
```
which is wrong, the `get` method returns a single variable.

**Comment by bestfriendai** [comment]
What would be the updated code?
