### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by rome2rome** [desprit/tg-ai-connector#15]
Can you create a docker image :) for non tech guy like me ;)

**Comment by desprit** [comment]
Yes, I will do. Was planning for a long time, will try to prepare tomorrow.

**Comment by desprit** [comment]
@rome2rome 

Done! Let me know if it doesn't work for you. I tested on MacOS and Linux.

https://github.com/desprit/tg-ai-connector#docker

```
docker run -d --rm -v /path/to/config.toml:/app/bot/config.toml desprit/tg-ai-connector:1.0.0
```

**Comment by rome2rome** [comment]
Works like charm :) Tanks :) You are the best. @desprit !!! 

P.S. For anyone else like me who will try to set up with docker, the first step is to create a config.toml file on (local machine /path/to/config.tomland then run the Docker container.
