### ISSUE TITLE
Add to whitelist using bot command

### ISSUE THREAD

**Issue by desprit** [desprit/tg-ai-connector#3]
Whitelist users and groups using bot command, e.g.:
```
/whitelist user_id
/whitelist username
/whitelist chat_id
```

**Comment by AliAkczaa** [comment]
but how can i do this?
20:29:20,498 tg-ai-connector DEBUG >>> Message received from user 175300xxxx, chat -86218xxxx
20:29:20,498 tg-ai-connector WARNING >>> Message from user 175300xxxx, chat -86218xxxx was blocked

**Comment by desprit** [comment]
@AliAkczaa 

This is a feature request, it's not implemented yet.

Right now the only was to whitelist someone is through config file.

**Comment by AliAkczaa** [comment]
> 

ok i see it in src/model.py. 
btw. nice job man :)

**Comment by desprit** [comment]
/whitelist and /blacklist commands have been added, you can see examples in readme
